server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:8085/eureka/,http://${eureka.instance.hostname}:8086/eureka/,http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: server

